# 站点信息
title: "音视频小白"                   # 网页 <title> 标签和首页标题                  :contentReference[oaicite:0]{index=0}
description: "分享个人的技术理解和见闻"       # meta 描述，有利于 SEO                 :contentReference[oaicite:1]{index=1}
author: "chli"                     # 作者信息，可用于模板中引用               :contentReference[oaicite:2]{index=2}

# 站点地址配置
url: "https://feiyangyy.github.io"  # 站点根 URL，不含尾部斜杠                 :contentReference[oaicite:3]{index=3}
baseurl: ""                             # 如果站点部署在子目录（如 /blog），则填 "/blog"；否则留空 :contentReference[oaicite:4]{index=4}

# 主题与外观
theme: jekyll-theme-cayman             # 使用官方主题 Cyberduck（Cayman）        :contentReference[oaicite:5]{index=5}
# remote_theme: pages-themes/minimal@v0.3.0  # 使用远程主题示例（需安装 jekyll-remote-theme 插件） :contentReference[oaicite:6]{index=6}

# 目录与文件过滤
exclude:                                # 构建时排除
  - README.md
  - node_modules
  - vendor
include:                                # 强制包含
  - _pages                              # 假设你有自定义页面目录

# 分页设置
paginate: 5                             # 首页每页显示 5 篇文章                  :contentReference[oaicite:7]{index=7}
paginate_path: "/page:num/"             # 分页链接格式，:num 会替换页码           :contentReference[oaicite:8]{index=8}

# URL 样式
permalink: /:categories/:year/:month/:day/:title/  # 自定义文章永久链接格式 :contentReference[oaicite:9]{index=9}

# Markdown 与高亮
markdown: kramdown                      # 指定使用 Kramdown 渲染器（Jekyll 默认） :contentReference[oaicite:10]{index=10}
kramdown:                               # Kramdown 专属选项                          :contentReference[oaicite:11]{index=11}
  input: GFM                            # 使用 GitHub Flavored Markdown 语法    :contentReference[oaicite:12]{index=12}
  auto_ids: true                       # 自动为标题生成 ID，用于锚点链接         :contentReference[oaicite:13]{index=13}
  toc_levels: 1..3                     # 目录深度：H1 到 H3                      :contentReference[oaicite:14]{index=14}

# 代码高亮
highlighter: rouge                     # 使用 Rouge 进行代码语法高亮             :contentReference[oaicite:15]{index=15}

# 插件（如有需要）
plugins:
  - jekyll-feed                        # RSS 订阅插件（要在 Gemfile 中添加依赖）    :contentReference[oaicite:16]{index=16}
  - jekyll-seo-tag                     # SEO 优化插件                            :contentReference[oaicite:17]{index=17}
